services:
  backend_test:
    container_name: anotaai_backend_test
    env_file: .env
    build: ./app
    ports:
      - ${API_LOCAL_PORT}:${API_LOCAL_PORT}
    networks:
    - anotaai_network
    environment:
      NODE_ENV: test
      DATABASE_URL: "postgres://anotaai_test:123456789@database_test:5432/anotaai_test"
      WAIT_HOSTS: database_test:5432
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    depends_on:
      - database_test
    command: >
      sh -c "
        /wait &&
        node ./sequelize/seeds/db.seed.js &&
        npm run test-coverage"
    volumes:
      - ./app/coverage:/usr/src/app/coverage
  database_test:
    container_name: anotaai_database_test
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    networks:
    - anotaai_network
    environment:
      POSTGRES_PASSWORD: 123456789
      POSTGRES_USER: anotaai_test
      POSTGRES_DATABASE: anotaai_test
networks: 
  anotaai_network:
    driver: bridge
