name: Heroku Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: anotaai

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Heroku Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "anotaifsp"
          heroku_email: "rhenandev@gmail.com"
          buildpack: "https://github.com/timanovsky/subdir-heroku-buildpack.git"
